# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./GeneratePlan.h \
    ./Control.h \
    ./DataStructure.h \
    ./ProgramLib.h \
    ./resource.h \
    ./COVID_19_Travel_System.h \
    ./CityDangerQuery.h \
    ./VehicleQuery.h \
    ./PlanViewer.h \
    ./Map.h
SOURCES += ./CityDangerQuery.cpp \
    ./GeneratePlan.cpp \
    ./Control.cpp \
    ./COVID_19_Travel_System.cpp \
    ./DataStructure.cpp \
    ./Main.cpp \
    ./Map.cpp \
    ./PlanViewer.cpp \
    ./VehicleQuery.cpp
FORMS += ./CityDangerQuery.ui \
    ./COVID_19_Travel_System.ui \
    ./PlanViewer.ui \
    ./VehicleQuery.ui
RESOURCES += COVID_19_Travel_System.qrc
